config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'login', to: 'welcome#login'
  get 'howto_export', to: 'welcome#howto_export'

  match "auth/twitter/callback" => "sessions#create", via: [:get, :post]
  match "signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  resources :users, only: [:show, :edit, :update]
  resources :playlists

end

app/models/playlist.rb
class Playlist
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :tracks, type: Array
  field :description, type: String

  belongs_to :user
  validates_presence_of :name, :tracks
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :provider, type: String
  field :uid, type: String
  field :name, type: String

  field :icon, type: String

  field :profile, type: String

  has_many :playlists
  validates_presence_of :name, :uid, :provider

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.icon = auth["info"]["image"]
      user.profile = auth["info"]["description"]
    end
  end
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  if !Rails.env.development?
    rescue_from Exception,                        with: :render_500
    #rescue_from ActiveRecord::RecordNotFound,     with: :render_404
    rescue_from ActionController::RoutingError,   with: :render_404
  end

  def routing_error
    raise ActionController::RoutingError.new(params[:path])
  end

  def render_404(e=nil)
    logger.info "Rendering 404 for: #{e.message}" if e
    if request.xhr?
      render json: { error: '404 error' }, status: 404
    else
      format = params[:format] == :json ? :json : :html
      render template: 'errors/404', formats: format, status: 404, layout: 'application', content_type: 'text/html'
    end
  end

  def render_500(e)
    logger.info "Rendering 500 for: #{e.message}" if e
    if request.xhr?
      render json: { error: '500 error' }, status: 500
    else
      format = params[:format] == :json ? :json : :html
      render template: 'errors/500', formats: format, status: 500, layout: 'application', content_type: 'text/html'
    end
  end

  def authenticate
    redirect_to controller: 'welcome', action: :login unless (!session[:user_id].nil?) && User.find(session[:user_id])
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/playlists_controller.rb
require 'csv'

class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, only: [:new, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])
    #binding.pry
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    begin
      file = playlist_params[:upload_file]
      file_content = file.read
      pl =
        if file_content =~ /NML/
          # traktor nml
          Traktor::NML.parse(file_content).map do |t|
            {
              title: t[:title],
              artist: t[:artist],
              genre: t[:genre],
              label: t[:label],
              playtime: t[:playtime],
              bpm: t[:bpm]
            }
          end
        else
          # iTunes Playlist
          File.open file.tempfile.path, 'rb', encoding: Encoding::UTF_16LE do |f|
            csv = CSV.new f, encoding: Encoding::UTF_16LE, col_sep: "\t", row_sep: :auto
            csv_ar = csv.map do |tr|
              {
                title: tr[0],
                artist: tr[1],
                genre: tr[5],
                label: nil,
                playtime: tr[7],
                bpm: nil
              }
            end
            csv_ar.delete_at 0
            csv_ar
          end
        end
    rescue => e
    end
    @playlist = Playlist.new( tracks: pl, name: playlist_params[:name], description: playlist_params[:description] )
    @playlist.user = current_user
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    if @playlist.user == current_user
      respond_to do |format|
        if @playlist.update(playlist_params)
          format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
          format.json { render :show, status: :ok, location: @playlist }
        else
          format.html { render :edit }
          format.json { render json: @playlist.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    if @playlist.user == current_user
      @playlist.destroy
      respond_to do |format|
        format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :description, :tracks, :upload_file)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by(provider: auth["provider"], uid: auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:oauth_token] = auth.credentials.token
    session[:oauth_token_secret] = auth.credentials.secret
    session[:user_info] = auth.extra
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    session[:oauth_token] = nil
    session[:oauth_token_secret] = nil
    session[:user_info] = nil
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find params[:id]
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if current_user == @user
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'Profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :profile, :icon)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def login
  end

  def howto_export
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_search_url(str)
    "https://www.google.com/search?q=#{URI.encode str}"
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta charset="utf-8"
    title #{yield :title} - Traxlist // Share playlist with listeners
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-static-top.navbar-inverse.navbar-collapse
      .container-fluid
        .navbar-header
          == link_to "Traxlist", "/", class: "navbar-brand"
        ul.nav.navbar-nav
          li
            == link_to "Discover Playlists", "/playlists"
          li
            == link_to "How to export", "/howto_export"
        ul.nav.navbar-nav.navbar-right
          - if current_user
            li
              = link_to "Upload", "/playlists/new"
            li
              = link_to "Sign out #{current_user[:name]}", "/signout"
          - else
            li
              = link_to "Sign in with Twitter", "/auth/twitter"

    .container
      == yield
      .row
    footer.footer
      .container
        p Traxlist - <a href="https://github.com/polamjag/traxlist">fork me in GitHub</a> - developed and maintained by <a href="https://about.polamjag.info/">@polamjag</a>

app/views/playlists/_form.html.slim
- content_for :title, "Upload playlist"

= form_for @playlist do |f|

  - if @playlist.errors.any?
    .alert.alert-danger
      h4 = "#{pluralize(@playlist.errors.count, "error")} prohibited this playlist from being saved:"
      ul
        - @playlist.errors.full_messages.each do |message|
          li = message

  .field.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control input-lg', placeholder: 'My awesome playlist'
  .field.form-group
    = f.label :description
    = f.text_field :description, class: 'form-control', placeholder: 'Mix at CLUB RAILS, performed on Feb. 15, 2014 '
  .field.form-group
    = f.label :playlist_file
    = f.file_field :upload_file
  .actions = f.submit class: 'btn btn-primary'

app/views/playlists/edit.html.slim
h1 Editing playlist

== render 'form'

hr

p
  = link_to 'Cancel and back to playlist', @playlist, class: "btn btn-default", "role" => "button"
  = link_to 'Delete playlist', @playlist, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-danger"

app/views/playlists/index.html.slim
h1 Discover Playlists

table.table.table-striped
  thead
    tr
      th Name
      th Uploaded by

  tbody
    - @playlists.each do |playlist|
      tr
        td = link_to playlist.name, playlist
        td = link_to playlist.user.name, playlist.user

app/views/playlists/list.html.slim
table.table.table-striped
  thead
    tr
      th Name
      th Uploaded by
      th Date

  tbody
    - Playlist.all.desc('_id').limit(30).each do |playlist|
      tr
        td = link_to playlist.name, playlist
        td = link_to playlist.user.name, playlist.user
        td = playlist.created_at

app/views/playlists/new.html.slim
h1 Upload playlist

.alert.alert-info
  | Need some help to uploading? See #{link_to "How to export playlist", "/howto_export", class: "alert-link"}

== render 'form'

app/views/playlists/show.html.slim
- content_for :title, "#{@playlist.name} by #{@playlist.user.name}"

- unless notice.nil?
  .alert.alert-info = notice

.row
  .col-sm-10
    .media
      - unless @playlist.user.icon.nil?
        .media-left.media-middle.pull-left
          = link_to image_tag(@playlist.user.icon, alt: "#{@playlist.user.name}'s icon", class: "media-object img-circle"), @playlist.user
      .media-body
        h3.media-heading
          | #{@playlist.name}
          | &nbsp;
          small by #{link_to @playlist.user.name, "/users/" + @playlist.user.id}
        p = @playlist.description
        p Uploaded at #{@playlist.created_at}
  - if @playlist.user == current_user
    .col-sm-2
      .pull-right
        = link_to edit_playlist_path(@playlist), class: "btn btn-default", "role" => "button" do
          span.glyphicon.glyphicon-pencil
          | Edit

.row
  table.table.table-striped
    thead
      tr
        th
        th #
        th Title
        th Artist
        th Genre
        th BPM
    tbody
      - @playlist.tracks.each_with_index do |track, index|
        tr
          td = link_to google_search_url("#{track['title']}+#{track['artist']}"), {target: "_blank", class: "btn btn-xs btn-default only-glyphicon", title: "Search for this track"} do
            span.glyphicon.glyphicon-search
          td = index + 1
          td = track["title"]
          td = track["artist"]
          td = track["genre"]
          td = track["bpm"]

.row.share-widgets
  h4 Share
  / Twitter
  a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-count="none" data-dnt="true"
    Tweet
  javascript:
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  / Tumblr
  a href="http://www.tumblr.com/share/link?url=#{request.original_url}" title="Share on Tumblr" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:81px; height:20px; background:url('https://platform.tumblr.com/v1/share_1.png') top left no-repeat transparent;"
    Share on Tumblr
  / Google+
  div class="g-plus" data-action="share" data-annotation="bubble" data-height="24"
  script src="https://apis.google.com/js/platform.js" async defer
    {lang: 'ja'}

app/views/users/_form.html.slim
- content_for :title, "Edit profile"

= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.label :profile
    = f.text_field :profile, class: "form-control"

  .actions = f.submit class: "btn btn-primary"

app/views/users/edit.html.slim
h1 Editing #{@user.name}'s profile

== render 'form'

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Provider
      th Uid
      th Name
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.provider
        td = user.uid
        td = user.name
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
- content_for :title, @user.name

- unless notice.nil?
  .alert.alert-info = notice

.row
  - if @user == current_user
    p
      == link_to "Edit profile", {action: :edit}, class: "btn btn-default"

  .media
    - unless @user.icon.nil?
      .media-left.media-middle.pull-left
        img.media-object.img-circle src="#{@user.icon}" alt="#{@user.name}'s icon"
    .media-body
      h2.media-heading = @user.name
      p = @user.profile

.row
  - if @user.playlists.length > 0
    h3 Recent playlists
    table.table.table-striped
      thead
        tr
          th Name
          th Uploaded at
      tbody
        - @user.playlists.each do |l|
          tr
            td = link_to l.name, l
            td = l.created_at
  - else
    p This user has no playlists yet.

app/views/welcome/howto_export.slim
- content_for :title, "How to export your playlist"

.row
  h1 How to export your playlist
  h2 Traktor
  p First, right click playlist to export then click "Export Playlist."
  img.img-responsive.img-thumbnail src="#{asset_path 'traktor-1.png'}"
  p Second, input Playlist title and select destination. <strong>You must choose "NML" in "Export Format."</strong>
  p Note that you should uncheck "Copy Tracks To Destination" to save disk space.
  img.img-responsive.img-thumbnail src="#{asset_path 'traktor-2.png'}"

  h2 iTunes
  p First, press key "Alt" to show menu, then select "File" &gt; "Library" &gt; "Export Playlist..."
  img.img-responsive.img-thumbnail src="#{asset_path 'itunes-1.png'}"
  p Next, select directory and input filename. <strong>You must select "Text files (*.txt)" in "Save as type."</strong>
  img.img-responsive.img-thumbnail src="#{asset_path 'itunes-2.png'}"

app/views/welcome/index.html.slim
- content_for :title, "Welcome"

div
  - if ! current_user
    .jumbotron style="text-align: center"
      h1 Share playlists with listeners
      p Sign in to upload playlists of Traktor (.nml) and iTunes (.txt)
      p
        = link_to "Sign in with Twitter", "/auth/twitter", class: "btn btn-lg btn-info"
      small We use your account information only for authentication and acquisition of your profiles.
  - else
    .row.text-center
      = link_to 'playlists/new', class: "btn btn-primary btn-lg" do
        span.glyphicon.glyphicon-plus-sign
        | Upload and share your playlist
      = link_to current_user, class: "btn btn-default" do
        span.glyphicon.glyphicon-user
        | View your profile
  .row
    h2 Recent uploads
    = render :template => "playlists/list"

app/views/welcome/login.html.slim
- if ! current_user
  == link_to "Sign in with Twitter", "/auth/twitter", class: "btn btn-lg btn-info"
- else
  == redirect_to :root